### ISSUE TITLE
not starting - authentication failed

### ISSUE THREAD

**Issue by sevi-kun** [arcolinux/archlinux-tweak-tool#9] opened 2023-04-04 07:53 UTC
Hey, 
I can't execute archlinux-tweak-tool. 
I'm on arcolinux and don't know what changed.

When running in a terminal I get the following after authenticating in the terminal:

---
polkit-agent-helper-1: error response to PolicyKit daemon: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: No session for cookie
==== AUTHENTICATION FAILED ====
Error executing command as another user: Not authorized

This incident has been reported.
---

Re-installing didn't help. What should I do?

**Comment by arcolinuxz** [comment] 2023-04-05 05:20
looks like you need somebody to authenticate your session

on ArcoLinuxD you have to do everything yourself

https://wiki.archlinux.org/title/Polkit

**Comment by ph767** [comment] 2023-04-14 09:11
![image](https://user-images.githubusercontent.com/127475615/231999844-5f9c67fa-2652-4c7b-8027-91e543b6ca25.png)

Gparted and other sudo-apps are running well.  And there is no polkit dialog window when i run ATT.

**Comment by arcolinuxz** [comment] 2023-04-14 10:10
switch to sddm and see

**Comment by ph767** [comment] 2023-04-14 10:20
With sddm and lightdm it works well. 

But i usually using startx with dwm with autostart script:
run /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

I checked other sudo gui-apps and when i run them i have gnome-polkit dialog. ATT is exception.

**Comment by arcolinuxz** [comment] 2023-04-14 13:18
that is why
check how we launch it
you can adapt your code to that

https://github.com/arcolinux/archlinux-tweak-tool/blob/master/usr/bin/archlinux-tweak-tool

this is what you need to change

**Comment by ph767** [comment] 2023-04-14 13:40
It works if i comment this two lines

```
session=$(loginctl show-session $(loginctl|grep $(whoami) | awk '{print $1}') -p Type | awk -F= '{print $2}' | grep "x11\|wayland")

test -z "$session" && echo "[ERROR] Failed to verify session for user." && exit 1
```
Will try to find legit workaround later.

**Comment by DeltaCopy** [comment] 2023-04-14 15:10
@ph767 

`pkexec '/usr/share/archlinux-tweak-tool/archlinux-tweak-tool.py'`

Does polkit prompt for a password ?

> But i usually using startx with dwm with autostart script:
run /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

Which user starts the polkit process, visible through `ps -ef | grep polkit`

Please also print output of:

`loginctl show-session $(loginctl|grep $(whoami) | awk '{print $1}') -p Type | awk -F= '{print $2}'`

Does it return anything ?

**Comment by ph767** [comment] 2023-04-14 19:10
`loginctl show-session $(loginctl|grep $(whoami) | awk '{print $1}') -p Type | awk -F= '{print $2}'`

Output is **tty** because **startx** doesn't set $XDG_SESSION_TYPE 
But when you are running WM via _startx_ u have _xinit_ process.

Im not very good at using git. 
So i show here my workaround to bypass this check:

session=$(loginctl show-session $(loginctl|grep $(whoami) | awk '{print $1}') -p Type | awk -F= '{print $2}' | grep "x11\|wayland")

# If xinit is running set session variable as X11
if [ "$(pidof xinit)" -ne 0 ]; then
    session="X11"
fi

test -z "$session" && echo "[ERROR] Failed to verify session for user." && exit 1`

**Comment by DeltaCopy** [comment] 2023-04-14 21:19
> Output is tty because startx doesn't set $XDG_SESSION_TYPE

That is exactly why the script doesn't rely on using that env var, as it is not guaranteed to be set across all systems.
Particularly if you are going into a system via TTY

We've seen cases like this before, where the session being used is a TTY.
ATT won't open since it cant verify the session.

Your solution may work, but it'll require testing across numerous desktop environments.

1. If you are on X11 your $DISPLAY env var should be set.
2. If you are on Wayland your $WAYLAND_DISPLAY should be set.

So just verify whether number 1 is indeed the case for you.

**Comment by DeltaCopy** [comment] 2023-04-15 12:18
@erikdubois 

[PR raised.](https://github.com/arcolinux/archlinux-tweak-tool-dev/pull/3)
This patch incorporate users in a TTY session.

I have tested and confirmed working in the following cases.

- Plasma: Wayland | X11 | TTY

Note. On Plasma I also tested the Ly display manager which uses TTY and the patch works there too.

- DWM | TTY
- Sway | Wayland
- XFCE | X11

**Pending test on Hyprland, as I don't have a system to test on currently.**

**Comment by DeltaCopy** [comment] 2023-04-19 07:20
@ph767 Update to the latest version of the archlinux-tweak-tool a patch has been applied to support users running in a tty session.
Closing this issue.

**Closed by DeltaCopy** 2023-04-19 07:20 UTC

**Comment by ph767** [comment] 2023-04-19 09:02
> @ph767 Update to the latest version of the archlinux-tweak-tool a patch has been applied to support users running in a tty session. Closing this issue.

It runs without any issue for me.
